### ISSUE TITLE
Could you share me with the full k600 dataset?

### ISSUE THREAD

**Issue by OliverHxh** [wengzejia1/Open-VCLIP#1]
Dear authors,

Thanks for your great work. I am currently working on this topic based on your repo. I find you only share part of the k600 dataset (only the val folder). Is it possible that you could provide me with the link to download the full k600 dataset (train, val, and test)? 

Thanks for your efforts on this work again!

**Comment by wengzejia1** [comment]
Hello, we appreciate your interest in our work. Regrettably I cannot provide access to the entire K600 dataset, and I encourage you to consider alternative sources for obtaining the required data.
