### ISSUE TITLE
Error with checkpoint weights

### ISSUE THREAD

**Issue by CarmelaCalabrese** [wengzejia1/Open-VCLIP#4]
Hi @wengzejia1 
here I am back again! A few questions on the weights:

1. I am trying your code for the testing part and when I try to load _openvclip-b16/swa_2_22.pth _ (I downloaded them from the Google Drive folder) I get the following error:

File "/Open-VCLIP/test_net.py", line 296, in test
    checkpoint = torch.load(custom_load_file, map_location='cpu')
  File "/root/miniconda3/envs/ivnet/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/ivnet/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: pickle data was truncated

It doesn't seem to happen with the other two files. Could it be corrupted?

2. Regarding these weights on Google Drive, do they represent \theta in Eq.6 of the paper or only \thetaB? In particular, which dataset do they refer to?
3. In the paper, you talk about Evaluation Protocol 3. So my question is: did you run only an intra-dataset or you tested also inter-dataset to check the open-set capability? Should I pretrain every-time on my personal dataset to get \thetaB?

Thanks again ;)

**Comment by wengzejia1** [comment]
Hi CarmelaCalabrese,

Thank you for your interest in our project.

**1. Checkpoint Loading Error**
It seems that a network issue might have caused the corruption of the downloaded file. Please attempt to download a new checkpoint to check if the problem persists.

**2. Weights**
The weights on Google Drive represent $\theta_B$ in Eq.6, and $data B$ refers to Kinetics-400. Therefore, when testing, ensure you apply the appropriate weights interpolation. This can be set using "TEST.PATCHING_RATIO $PATCHING_RATIO," as demonstrated in the testing scripts.

**3. About Testing**
I'm unsure if I fully comprehend your question. We train our model on the Kinetics-400 dataset initially and subsequently test the model on UCF / HMDB / K600-others, following different Evaluation Protocols.

Thank you for bringing these concerns to our attention. If you have any further questions or need additional clarification, feel free to ask.

Best.

**Comment by CarmelaCalabrese** [comment]
Hi @wengzejia1,
thank you, it's clear.

**1. Checkpoint Loading Error**
Yesterday I downloaded several times and didn't work. Today I downloaded differently and the file is okay!

**2. Weights**
Sorry, probably I missed this part in the paper, now I see it. What do you mean by saying "when testing, ensure you apply the **appropriate** weights interpolation"? 

**3. About Testing**
You answered my question and I didn't read carefully this part of the paper.

Thank you again for your kindness!

**Comment by wengzejia1** [comment]
**Reply to "2. Weights"**
The weights provided on Google Drive correspond to $\theta_B$ in Eq. 6 of our paper, while the original CLIP weights correspond to $\theta_A$ in Eq. 6. Our paper will do the weights interpolation between $\theta_A$ and $\theta_B$, which is controlled by the "TEST.PATCHING_RATIO" (as demonstrated in the "script/testing/temporal_test_b16/k600.sh" file for example), which  corresponds to $\lambda$ in Eq.6.

My latest response just emphasizes the importance of not forgetting to set the $\lambda$ as indicated.
