### ISSUE TITLE
Cannot decompress the Kinetics-600 tar.gz file

### ISSUE THREAD

**Issue by ZMHH-H** [wengzejia1/Open-VCLIP#5]
Hi, thanks for your great job! I download the K600 validation file via the link provided in the readme file, but some of them can not be decompressed (val.tar.gz.1,val.tar.gz.2,val.tar.gz.3). Could you please check if the files are broken?

**Comment by wengzejia1** [comment]
Hi, you can try the following command:
"cat val.tar.gz.* >> test.tar.gz"
"tar -zxf test.tar.gz"

**Comment by ZMHH-H** [comment]
thank you, it works
