### ISSUE TITLE
Is a list of captions for Kinetics-400 available??

### ISSUE THREAD

**Issue by rB080** [wengzejia1/Open-VCLIP#6]
Is there a csv/json/txt/ etc file containing captions for all kinetics videos?

**Comment by wengzejia1** [comment]
Hi, in our extended version "Building an open-vocabulary video clip model with better architectures, optimization and data", we have constructed captions for kinetics videos with the help of BLIP-2 and LLaMA-2 chat for improved performance on zero-shot action recognition and video-text retrieval. 

The  k400 caption file have been uploaded to the 'blip_llama2_caption' folder at present, and the subsequent code will be updated soon.

**Comment by rB080** [comment]
Thank you so much for the captions file!
