### ISSUE TITLE
Problems with testing code

### ISSUE THREAD

**Issue by CarmelaCalabrese** [wengzejia1/Open-VCLIP#7]
Hi @wengzejia1,
here I am back again. I am trying your testing code, exactly as you report on the main page of the repository but I have a very strange problem. The code stucks on this line of test_net.py:

for cur_iter, (inputs, labels, video_idx, time, meta) in enumerate(
        test_loader
    ):

It seems there are problems to enumerate and I got a simple:
123369 Killed 

This number changes everytime I try. Could you help me to understand it?

I am trying on UCF101. I have simply downloaded the data as you linked here (https://github.com/open-mmlab/mmaction2/blob/main/tools/data/ucf101/download_videos.sh), do you mean to run all the pipeline described here: https://github.com/open-mmlab/mmaction2/tree/main/tools/data/ucf101 ? It's not clear :/ Do you need videos or frames?

Thank you again in advance!

**Comment by wengzejia1** [comment]
Hi, we just need the videos to run the testing process.
