### ISSUE TITLE
About training cost

### ISSUE THREAD

**Issue by zyuhan1999** [wengzejia1/Open-VCLIP#8]
Hi! @wengzejia1 

Could you please provide the memory requirement per GPU and estimated training time for Open-VCLIP on the K400?

Thanks!

**Comment by wengzejia1** [comment]
Hi, I run Open-VCLIP B/16 on 8 * 32GB V100, and it takes about one day.

If your GPU memory is not enough, you can employ checkpointing techniques by configuring the settings to "MODEL.USE_CHECKPOINT True" and "MODEL.STATIC_GRAPH True," as demonstrated in the script located at "script/training/temporal_l14/train_tclipl14_interpolation_0.0-0.6_ratio0.5.sh".  

It's worth noting that this approach may extend the overall training time.

**Comment by zyuhan1999** [comment]
> Hi, I run Open-VCLIP B/16 on 8 * 32GB V100, and it takes about one day.
> 
> If your GPU memory is not enough, you can employ checkpointing techniques by configuring the settings to "MODEL.USE_CHECKPOINT True" and "MODEL.STATIC_GRAPH True," as demonstrated in the script located at "script/training/temporal_l14/train_tclipl14_interpolation_0.0-0.6_ratio0.5.sh".
> 
> It's worth noting that this approach may extend the overall training time.

Thanks a lot :)
